config/routes.rb
Rails.application.routes.draw do
  resources :roles
  resources :articles, only: [:index, :show]
  resources :categories do
    resources :articles, only: [:index, :show]
  end
  devise_for :users, path: 'auth'
  root to: 'home#index'
  
  namespace :admin do
    get '/dashboard' => 'dashboard#index'
    resources :users
    resources :articles
    resources :categories, except: :show
  end
  get '/aboutus' => 'aboutus#index'
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :users
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_role, only: [:show, :edit, :update, :destroy]

  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
  end

  # GET /roles/new
  def new
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles 
  # POST /roles.json
  def create
    @role = Role.new(role_params)

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Role was successfully created.' }
        format.json { render :show, status: :created, location: @role }
      else
        format.html { render :new }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1
  # PATCH/PUT /roles/1.json
  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_url, notice: 'Role was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def role_params
      params.require(:role).permit(:name)
    end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/roles/_form.html.haml
= form_for @role, html: { class: "form-horizontal", role: "form" } do |f|
  -if @role.errors.any?
    .alert.alert-danger.alert-dismissable{role: "alert"}
      %button.close{type: "button", data: {dismiss: "alert"} }
        %span{aria: {hidden: "true"} } &times;
        %span.sr-only Close
      %h4= "#{pluralize(@role.errors.count, "error")} prohibited this role from being saved:"

      %ul
        - @role.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :name, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :name, class: 'form-control'
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit class: 'btn btn-primary'

app/views/roles/edit.html.haml
.page-header
  = link_to roles_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to @role, class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-info-sign
    Show
  %h1 Editing role

= render 'form'

app/views/roles/index.html.haml
.page-header
  = link_to new_role_path, class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-plus
    New Role
  %h1 Listing roles

.table-responsive
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th ID
        %th Name
        %th Show
        %th Edit
        %th Delete

    %tbody
      - @roles.each do |role|
        %tr
          %td= role.id
          %td= role.name
          %td= link_to 'Show', role
          %td= link_to 'Edit', edit_role_path(role)
          %td= link_to 'Destroy', role, data: { confirm: 'Are you sure to delete this user?' }, method: :delete

app/views/roles/new.html.haml
.page-header
  = link_to roles_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  %h1 New role

= render 'form'

app/views/roles/show.html.haml
.page-header
  = link_to roles_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to edit_role_path(@role), class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-pencil
    Edit
  %h1 Show role

%dl.dl-horizontal
  %dt Name:
  %dd= @role.name