config/routes.rb
Rails.application.routes.draw do
  resources :roles
  resources :articles, only: [:index, :show]
  resources :categories do
    resources :articles, only: [:index, :show]
  end
  devise_for :users, path: 'auth'
  root to: 'home#index'
  
  namespace :admin do
    get '/dashboard' => 'dashboard#index'
    resources :users
    resources :articles
    resources :categories, except: :show
  end
  get '/aboutus' => 'aboutus#index'
end

app/models/user.rb
class User < ApplicationRecord
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  belongs_to :role
  has_many :articles
  validates :email, :role, presence: true

  def admin?
    role.name == 'admin' 
  end
end

app/controllers/admin/users_controller.rb
module Admin  
  class UsersController < AdminController
    before_action :set_user, only: [:show, :edit, :update, :destroy]
    def index
      @users = User.all 
    end
    def show
    end
  
    # GET /roles/new
    def new
      @user = User.new
    end
  
    # GET /roles/1/edit
    def edit

    end
  
    # POST /roles 
    # POST /roles.json
    def create
      @user = User.new(user_params)
  
      respond_to do |format|
        if @user.save
          format.html { redirect_to [:admin, @user], notice: 'Role was successfully created.' }
          format.json { render :show, status: :created, location: @user }
        else
          format.html { render :new }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # PATCH/PUT /roles/1
    # PATCH/PUT /roles/1.json
    def update
      respond_to do |format|
        if @user.update(user_params)
          flash[:notice] = "You just update User !"
          format.html { redirect_to admin_user_path, notice: 'Role was successfully updated.' }
          format.json { render :show, status: :ok, location: @user }
        else
          format.html { render :edit }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /roles/1
    # DELETE /roles/1.json
    def destroy
      @user.destroy
      respond_to do |format|
        format.html { redirect_to admin_users_path, notice: 'Role was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_user
        @user = User.find(params[:id])
      end
  
      # Never trust parameters from the scary internet, only allow the white list through.
      def user_params
        params.require(:user).permit(:email, :password, :role_id)
      end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.haml
= simple_form_for [:admin, @user], html: { class: "form-horizontal", user: "form" } do |f|
  -if @user.errors.any?
    .alert.alert-danger.alert-dismissable{user: "alert"}
      %button.close{type: "button", data: {dismiss: "alert"} }
        %span{aria: {hidden: "true"} } &times;
        %span.sr-only Close
      %h4= "#{pluralize(@user.errors.count, "error")} prohibited this role from being saved:"

      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :email, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.input :email, label: false, class: 'form-control'
  .form-group
    = f.label :role, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.association :role, label: false, class: 'form-control'
  - unless @user.persisted?
    .form-group
      = f.label :password, class: 'col-sm-2 control-label'
      .col-sm-10
        = f.input :password, label: false, class: 'form-control'
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit class: 'btn btn-primary'

app/views/admin/users/edit.html.haml
.page-header
  = link_to roles_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to @role, class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-info-sign
    Show
  %h1 Editing role
  
= render 'form'

app/views/admin/users/index.html.haml
.page-header
  = link_to new_admin_user_path, class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-plus
    New User
  %h1 Listing Users

.table-responsive
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th ID
        %th Email
        %th Role
        %th Show
        %th Edit
        %th Delete

    %tbody
      - @users.each do |user|
        %tr
          %td= user.id
          %td= user.email
          %td= user.role.try(:name)
          %td= link_to 'Show', admin_user_path(user)
          %td= link_to 'Edit', edit_admin_user_path(user)
          %td= link_to 'Destroy', admin_user_path(user), data: { confirm: 'Are you sure to delete this user?' }, method: :delete

app/views/admin/users/new.html.haml
.page-header
  = link_to admin_users_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  %h1 New User


= render 'form'

app/views/admin/users/show.html.haml
.page-header
  = link_to admin_users_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to edit_admin_user_path(@user), class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-pencil
    Edit
  %h1 Show User

%dl.dl-horizontal
  %dt Email:
  %dd= @user.email
  %dt Role:
  %dd= @user.role.name



-# = render 'form'